refactoring, GetAll() and Persist(TShirt tshirt) still not working..
app won’t build:

/Users/sta/repo/C-Shirts/C-ShirtsNet/Modules/HomeModule.cs(31,31):
Error CS1579: foreach statement cannot operate on variables of type
`System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<CShi
rts.Persistence.Models.TShirt>>' because it does not contain a
definition for `GetEnumerator' or is inaccessible (CS1579)
(C-Shirts.Web)